### ISSUE TITLE
Remove filter from Facets

### ISSUE THREAD

**Issue by gabiudrescu** [BitBagCommerce/SyliusElasticsearchPlugin#109]
I wanted to disable the Pricing Facet from site search and I thought about doing this by removing the PriceFacet from Registry. 

Unfortunately, the Registry does not have a remove method. would it be such a bad idea to implement one?

**Comment by leszczuu** [comment]
In current version - v4.0.2 - pricing facet is not enabled by default and You have to override definiton to add it, if You want to add or disable everywhere this can be done with just container configuration.
If You need to dynamically decide which facets will be used You can override registry and add some kind of filtering.
This is not much code, You can put enabling/disabling logic there, and this is currently preferred method to customize facets registry.
I am not sure where would You call 'removeFacet' method from if it existed, it does not make sense to use it like 'addFacet' is used in container config. 
Because there is no code in plugin that uses this, I think there is benefit of adding just this method, users would still need to customize other things to use it.
