### ISSUE TITLE
Use filter with range for integer attribute

### ISSUE THREAD

**Issue by jbcr** [BitBagCommerce/SyliusElasticsearchPlugin#124]
On product I have an integer attribute.

How to change the filter to display range instead of each value?

**Comment by chadyred** [comment]
You have to create a new attribute type with 2 value, and register it as a new type. Then you have to create your own filter (like price min and price max).

Then Elastic have to be updated with your new field in order to be filtered in the listing product through ElasticSearch. In other word, you need to use a PropertyBuilder to do this last action to enrich elastic document with your requested information with your data?

**Comment by jbcr** [comment]
Thanks for your answer.

I want to extend the bundle to change the behavior for all attribute integer filters. This filter must be displayed only wend its need (the actual behavior)

I want this for all integer attribute on my product (it's not the price):

![image](https://user-images.githubusercontent.com/51637606/83162647-49e96980-a10a-11ea-80c3-1584e6999ee4.png)

**Comment by jbcr** [comment]
Thank you, after more thought I understood your idea.
