### ISSUE TITLE
Error trying to use a generic form to search items with bitbag_sylius_elasticsearch_plugin_shop_search

### ISSUE THREAD

**Issue by joenilson** [BitBagCommerce/SyliusElasticsearchPlugin#154]
I'm trying to use the site wide search as is in the demo.bitbag.shop, but searching for any item like the cactus or the chair i don't get results.

I'm with a sylius 1.8.6 and the plugin was installed correctly, i set a code block like this in the topbar:

```
<div class="item">
    <form action="{{ path('bitbag_sylius_elasticsearch_plugin_shop_search') }}" method="get">
        <div class="ui mini  left icon input">
            <input type="text" class="promt" placeholder="{{ 'sylius.ui.search'|trans }}..." name="name" />
            <i class="search icon"></i>
        </div>
    </form>
</div> 
```

It get me in to the result page but without items, as in the demo. 

In my installation the taxon search that uses autocomplete is working correctly.

Please can confirm if that is a bug or is a misconfiguration?.

**Comment by crackgm** [comment]
You get no items because your input name doesn't match name required by SearchType (BitBag\SyliusElasticsearchPlugin\Form\Type\SearchType). This form requires prefix and query parameters.

You should instead use:
`<input type="text" class="promt" placeholder="{{ 'sylius.ui.search'|trans }}..." name="bitbag_elasticsearch_search[box][query]" />`

or extend form type by yourself.

Also if you want to use form rendering provided by SearchType, you can use `{{ sonata_block_render_event('sylius.shop.layout.header') }}` in your _header.html.twig file.
