### ISSUE TITLE
Optimalization for big data

### ISSUE THREAD

**Issue by cv65kr** [BitBagCommerce/SyliusElasticsearchPlugin#17]
Hello,
My database has a 400k products, our target is 2mln, 3k taxons.
Every product have a minimum 2 attributes, so product_attributes table have a huge size.

If I try run taxon page then I have a OutOfMemoryException, any ideas how to optimize this plugin?

**Comment by bitbager** [comment]
Hi!

We have not tested the plugin against that much products and that being said, at this moment there's not much we can do about it without a specific case. 

You can either contact us on the mikolaj.krol@bitbag.pl email to discuss potential cooperation or provide a described PR with optimizations yourself.

**Comment by bitbager** [comment]
Perhaps this might be helpful - https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/273

**Comment by axotion** [comment]
I found a potential fix/workaround for your problems

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/cookbook/speed-up-populate-command.md#usage

**Comment by psihius** [comment]
I found the culprit for the insane memory usage:

```BitBag\SyliusElasticsearchPlugin\PropertyBuilder\AttributeTaxonsBuilder``` on line 84
```$productAttributes = $this->productAttributeValueRepository->findAll();``` 
Here it selects the whole `sylius_product_attribute_value` table, and that table is huge - we have almost 2 million records in that table, since per each product there are 2 to 10 attribute values.

```BitBag\SyliusElasticsearchPlugin\PropertyBuilder\OptionTaxonsBuilder``` actually does the same with ```$optionValues = $this->productOptionValueRepository->findAll();``` but in our case we do not have an issue with it because we have none. If someone has a lot of options on products - will face the same issue.

**Comment by bitbager** [comment]
Works now :)
