### ISSUE TITLE
Options filter not populated on product creation

### ISSUE THREAD

**Issue by t-n-y** [BitBagCommerce/SyliusElasticsearchPlugin#232]
When i create configurable product, with options, it doesn't populate the options taxons.
When i go to the products-list page, i don't see the options in the filter form. I have to do a manual populate to see them on the form

**Comment by DominikWolos** [comment]
Hi @t-n-y,
I think I've reproduced the issue you are reporting, did you try to add variant of configurable product before manually populating?

**Comment by t-n-y** [comment]
Hi @DominikWolos 
Yes i am creating a configurable product, then i generate the variants

**Comment by t-n-y** [comment]
Hi, 

do you have any idea if this issue will be fixed soon ?

**Comment by leszczuu** [comment]
I've tested with version "v4.0.2", I tried  both:
![image](https://github.com/user-attachments/assets/10a74382-477e-46a0-a691-54521910ebf3)
With option matching I did not have to generate variants - product was indexed in ES properly,
with attributes I tried product with 1 text attribute, and after creating variant, product was indexed in ES.

closing as I cannot reproduce, there is a chance it was fixed with recent 4.0.x version
