### ISSUE TITLE
10 products, 9 per page. Second page not found.

### ISSUE THREAD

**Issue by damonsson** [BitBagCommerce/SyliusElasticsearchPlugin#26]
There is a problem with pagination if products = **per page** + **1**.

**Comment by bitbager** [comment]
Is it fixed? CC @patrick477

**Comment by BabkoSergey** [comment]
> There is a problem with pagination if products = **per page** + **1**.


1. Redefine the bitbag_sylius_elasticsearch_plugin.finder.shop_products service
2. In the classroom
final class ShopProductsFinder implements ShopProductsFinderInterface
public function find (array $ data): Pagerfanta {
....
you need to swap the installation lines setCurrentPage and setMaxPerPage

so that
products-> setMaxPerPage ($ data [PaginationDataHandlerInterface :: LIMIT_INDEX]);
        $ products-> setCurrentPage ($ data [PaginationDataHandlerInterface :: PAGE_INDEX]);

Everything starts to work

**Comment by shadypierre** [comment]
@BabkoSergey PR #20 already fix this issue :)

This issue should be closed.

**Comment by bitbager** [comment]
Thanks!
