### ISSUE TITLE
Same Attributes on multiple taxons brings to many filter values per taxon

### ISSUE THREAD

**Issue by TELLO0815** [BitBagCommerce/SyliusElasticsearchPlugin#73]
We use same attributes for multiple taxons. Like for fixtures... Im sure if you sell t-shirts it is o.k. to see all the time all values from the attributes (Like Size S, M, L). And if you filter by S you may get "not items".
But in our case is this a problem. We want to show only the attribute values from this taxon im in.
I think there must be a option about this behavior.

**Comment by shurco** [comment]
This problem is very actual. Maybe you have any decision?

**Comment by jcgdjob** [comment]
I solved it by:

\Repository\ProductAttributeValueRepository.php
\RepositoryProductAttributeValueRepositoryInterface

added `getUniqueAttributeValuesByTaxon` function to filter attributes that only in current taxon (including sub taxon)

\Form\Type\ChoiceMapper\ProductAttributesMapper.php

call `getUniqueAttributeValuesByTaxon` instead

\Form\Type\ProductAttributesFilterType.php

due to the changes on ProductAttributesMapper, ProductAttributesFilterType required to update

**Comment by leszczuu** [comment]
With current version - v4.0.2 - this problem is no longer applicable:
In search results only values from results are shown:
![image](https://github.com/user-attachments/assets/17e183d4-91d8-42a4-be9d-d9be900c7e28)
In product list only values from products inside taxon are shown:
![image](https://github.com/user-attachments/assets/fee4425a-336c-42ec-aefe-ec02a68fbdd7)
